name: Lint, test and build

on: pull_request

jobs:
  lint_test_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
        mongodb-version: ["6.0.3"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Type-check, lint
        run: yarn lint:fix

      - name: Test apps
        run: yarn run test
        env:
          CI: true
          NODE_ENV: test
          MONGODB_VERSION: ${{ matrix.mongodb-version }}
